### ISSUE TITLE
Temp Solution

### ISSUE THREAD

**Issue by mikegeig** [sinbad/Unity2017ParticleIssues#1]
Howdy, saw you post this on Twitter. The seeming double play is a bug. You can slightly remember the positional issues however. If you change your instantiation code to this you won't get the positional offsets anymore:

`var obj = Instantiate (particlePrefab, new Vector3 (-100, 10, 0), Quaternion.identity) as GameObject;
var p = obj.GetComponent<ParticleSystem> ();  
p.Play ();`

**Comment by sinbad** [comment]
Thanks for the heads-up!

I've actually worked around it a different way, by dropping the subemitter link (seems I didn't really need it anyway). Good to know there's another work around as well, although that would not work for my real game, since as I mentioned in the video I'm using a pool of objects which I have to re-use; a one-time fix at Instantiate time would only fix it for the first use. Thanks anyway though!
